package com.dmadev.model;

import jakarta.persistence.*;
//
//create table Car(
//        id int primary key generated by default as identity ,
//        person_id int references Person(id) on delete set null,
//        model varchar(100) not null ,
//        engine_capacity int check ( engine_capacity>0) not null ,
//        color varchar,
//        electric bool not null ,
//        hybrid bool not null ,
//        type_body varchar not null
//        );

@Entity
@Table(name = "Car")
public class Car {

    @Id
    @Column(name = "id")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;

    @ManyToOne
    @JoinColumn(name = "person_id",referencedColumnName = "id") //в таблице Car -person_id в первичной id
    private Person owner;

    @Column(name = "model")
    private String model;

    @Column(name = "engine_capacity")
    private int engineCapacity;

    @Column(name = "color")
    private String color;

    @Column(name = "hybrid")
    private boolean hybrid;

    @Column(name="electric")
    private boolean electric;

    @Column(name = "type_body")
    @Enumerated(EnumType.STRING)
    private TypeBodyCar typeBody;

    public Car() {
    }

    public Car( String model, int engineCapacity, String color, boolean hybrid,boolean electric, TypeBodyCar typeBody) {
        this.model = model;
        this.engineCapacity = engineCapacity;
        this.color = color;
        this.hybrid = hybrid;
        this.electric=electric;
        this.typeBody = typeBody;
    }


    public boolean isElectric() {
        return electric;
    }

    public void setElectric(boolean electric) {
        this.electric = electric;
    }

    public String getModel() {
        return model;
    }

    public int getEngineCapacity() {
        return engineCapacity;
    }

    public String getColor() {
        return color;
    }

    public boolean isHybrid() {
        return hybrid;
    }

    public TypeBodyCar getTypeBody() {
        return typeBody;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Person getOwner() {
        return owner;
    }

    public void setOwner(Person owner) {
        this.owner = owner;
    }

    public void setModel(String model) {
        this.model = model;
    }

    public void setEngineCapacity(int engineCapacity) {
        this.engineCapacity = engineCapacity;
    }

    public void setColor(String color) {
        this.color = color;
    }

    public void setHybrid(boolean hybrid) {
        this.hybrid = hybrid;
    }

    public void setTypeBody(TypeBodyCar typeBody) {
        this.typeBody = typeBody;
    }
}
